### ISSUE TITLE
Get property types of a Model

### ISSUE THREAD

**Issue by ad-on-is** [ad-on-is/adonis-autoswagger#2]
`model.$columnsDefinitions` does not provide property types, except for datetime properties.

**Comment by thetutlage** [comment]
Yes, because there is no way to make it work on a wide range of data types. In order to get the types of a property in TypeScript one will have to use Reflection which is very limited in nature and does not work beyond standard data types like `string`, `number` and so on.

Also, should the API be concerned with the model data types? For example: I can have a model property that accepts a JSON data type, but from the API I want a string and then attach some meta-data to it and then save it as JSON?

---

Finally, you can rely on the database schema to get more accurate data types. 

```ts
import Database from '@ioc:Adonis/Lucid/Database'

const columns = await Database.connection().columnsInfo(Model.table)
console.log(columns)
```

**Comment by ad-on-is** [comment]
Ah, I see, it's a technical limitation. Thank you for clarifying.

>> Finally, you can rely on the database schema to get more accurate data types.

That would work for properties referenced to columns, but leaves out computed properties.

Another approach I was thinking of, would be to "simply" read the file contents and parse all `public <var>:<type>`

**Comment by ad-on-is** [comment]
Solved by parsing the files instead.
