### ISSUE TITLE
ignore some models

### ISSUE THREAD

**Issue by rbartholomay** [ad-on-is/adonis-autoswagger#42]
Hi.

is can hide/ignore some routes via 

```
  ignore: [
    "/swagger/json",
    "/swagger/docs",
    "/uploads/*",
    "/admin/*",
```

it possibile to hide also Models?  I did not want to list models for an ignored path like '/admin/'

Bye, René

**Comment by ad-on-is** [comment]
Models and paths are not related to each other. AutoSwagger grabs all the necessary info (models, interfaces, paths) independently and constructs the paths based on the provided comments.

It would be possible, but what if you still reference a hidden model somewhere and forget about the fact, that you ignored it? Will be hard to debug.

So to properly implement it on our side, this would introduce some additional if/else statements that might complicate things too much and without much benefit. i.e. as a consumer of an API, I think people spend most of their time looking at the paths, instead of the models.

Also.. If you use `AutoSwagger.default.rapidoc()` models aren't even listed there.

**Comment by rbartholomay** [comment]
👍 ok, thanks for clearify...
