### ISSUE TITLE
A way to get data in json?

### ISSUE THREAD

**Issue by FabriceGaillard** [ad-on-is/adonis-autoswagger#57]
Hi, Is there a way to get data in json format ?

**Comment by ad-on-is** [comment]
Currently, not. What would be the use case?

**Comment by FabriceGaillard** [comment]
To parse data, to filter it depending on some conditions

**Comment by ad-on-is** [comment]
`docs()` returns a stringified YAML. You should be able convert it back into json.

**Comment by FabriceGaillard** [comment]
Yes, i could use a package for this, but don't you convert js to yaml in this package? It Can be interesting to add in config file the output format wanted eventually.

**Comment by ad-on-is** [comment]
Yes, I do convert it, and it additionally saves a swagger.yaml file, which is used in production mode.

When you run the adonisJS app in dev mode, everything works seamlessly. However, when you deploy it to production, you MUST execute `node ace docs:generate` command, to generate the swagger.yml file, since in production you obviously don't have all the necessary references to the *.ts files and their comments, etc.

In this case, Autoswagger would have to create two file, swagger.yaml and swagger.json, to make it production ready.

**Comment by FabriceGaillard** [comment]
Ok thx for the explications. I think it could be a good option to have the choose of the output format. Autoswagger would have to create only one file depending of options defined in config/swagger.ts

**Comment by ad-on-is** [comment]
You're lucky I'm bored right now. `AutoSwagger.json()` is now implemented in version 2.14.x 😅 See the docs.

**Comment by FabriceGaillard** [comment]
Thx!
